server:
  port: 80

spring:
  application:
    name: cloud-consumer-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
      #defaultZone: http://eureka7001.com:7001/eureka  #单机版
  instance:
    instance-id: order80
    prefer-ip-address: true  #点进去左下角会显示ip
    #Eureka 客户端像服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    #lease-renewal-interval-in-seconds: 1
    #Eureka 服务端收到最后一次心跳后等待时间上线，单位为秒（默认是90秒），超时将剔除服务
    #lease-expiration-duration-in-seconds: 2