server:
  port: 2001

spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useSSL=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root


logging:
  level:
    io:
       seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml

feign:
  hystrix:
    enabled: true