server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启注册中心动态创建路由功能
      routes:
        - id: payment_routh #路由id要求唯一  建议与服务名匹配
          #uri: http://localhost:8001 #匹配路由的服务器地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配提供服务的路由地址
          predicates:
          - Path=/payment/get/**   #路由相匹配的地址
          #- After=2020-10-15T20:17:12.180+08:00[Asia/Shanghai] #规定时间之前不能访问
          #- Before=2020-10-15T21:17:12.180+08:00[Asia/Shanghai] #规定时间之后不能访问
          #- Between=2020-10-15T20:17:12.180+08:00[Asia/Shanghai],2020-10-15T21:17:12.180+08:00[Asia/Shanghai]
          #- Cookie=username,zhangsan  #访问路径 必须带 --cookie"username=zhangsan"
          #- Hander=X-Request-Id,/d+  #请求路径 必须带 -H"X-Request-Id:正数"
          #- Host=**.baidu.com  #请求路径 必须带 -H"Host:com.baidu.com"
          #- Method=GET  #请求方法是Get才能访问
          #- Query=username,\d+  #请求路径 必须接 ?username=正数

        - id: payment_routh2 #路由id要求唯一  建议与服务名匹配
          #uri: http://localhost:8001 #匹配路由的服务器地址
          uri: lb://CLOUD-PROVIDER-SERVICE  #匹配提供服务的路由地址
          predicates:
          - Path=/payment/lb/**   #路由相匹配的地址

eureka:
  instance:
    hostname: cloud-gateway-service  #eureka 服务端的实例名字

  client:
    register-with-eureka: true #表示不向注册中心注册自己
    fetch-registry: true #表示自己就是注册中心，职责是维护服务实例，并不需要去检索服务
    # 设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #defaultZone: http://eureka7001.com:7001/eureka  #单机版