server:
  port: 9003

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos地址